import { Scene, Engine, AbstractMesh, Mesh, int, StandardMaterial, ArcRotateCamera } from "babylonjs";
import "babylonjs-loaders";
import "babylonjs-gui";
import { SelectionPanel, TextBlock } from "babylonjs-gui";
export declare class App {
    private canvas;
    scene: Scene;
    engine: Engine;
    cptLaine: int;
    textBox: SelectionPanel;
    text: TextBlock;
    mouton1: boolean;
    available1: string;
    timing: int;
    timersec: int;
    plane: Mesh;
    matcollect: StandardMaterial;
    avancement: int;
    camera: ArcRotateCamera;
    constructor(canvas: HTMLCanvasElement);
    run(): void;
    CreateScene(): Scene;
    CreateSky(): void;
    CreateMouton(): Promise<void>;
    Mouton1OnClick(self: App): void;
    CreateCptLaine(): void;
    Timer(self: App): void;
    Waiting(self: App): void;
    CreateEnvironment(): Promise<void>;
    CreateController(): void;
    CreateObjects(): void;
    CreateActions(obj: AbstractMesh): void;
    ClickMamie(self: App): void;
    CreateChooseYourOutfit(): void;
    ClickOutfit(self: App): void;
    CreateCutScene(self: App): void;
    SecondAnimation(self: App): void;
    AfterCutScene(self: App): void;
    CreatePersonnage(): Promise<void>;
    CreateStartRunway(): void;
}
